PATH := ${PATH}:../mauve_snapshot_2011-08-19

454Junior-1-newbler: ../assemblies/newbler/454Junior-1.fna ../annotations/280_flxplus.gbk
	rm -f 454Junior-1-newbler
	ln -s ../assemblies/newbler/454Junior-1.fna 454Junior-1-newbler

454Junior-1-newbler_scores/chromosomes.txt: 454Junior-1-newbler ../annotations/280_flxplus.gbk
	mauvego 454Junior-1-newbler ../annotations/280_flxplus.gbk 454Junior-1-newbler

454Junior-2-newbler: ../assemblies/newbler/454Junior-2.fna ../annotations/280_flxplus.gbk
	rm -f 454Junior-2-newbler
	ln -s ../assemblies/newbler/454Junior-2.fna 454Junior-2-newbler

454Junior-2-newbler_scores/chromosomes.txt: 454Junior-2-newbler ../annotations/280_flxplus.gbk
	mauvego 454Junior-2-newbler ../annotations/280_flxplus.gbk 454Junior-2-newbler

454Junior-both-newbler: ../assemblies/newbler/454-Junior-1+2.fna ../annotations/280_flxplus.gbk
	rm -f 454Junior-both-newbler
	ln -s ../assemblies/newbler/454-Junior-1+2.fna 454Junior-both-newbler

454Junior-both-newbler_scores/chromosomes.txt: 454Junior-both-newbler ../annotations/280_flxplus.gbk
	mauvego 454Junior-both-newbler ../annotations/280_flxplus.gbk 454Junior-both-newbler

MiSeq-280-contigs-velvet: ../assemblies/velvet/MiSeq-280-contigs.fna ../annotations/280_flxplus.gbk
	rm -f MiSeq-280-contigs-velvet
	ln -s ../assemblies/velvet/MiSeq-280-contigs.fna MiSeq-280-contigs-velvet

MiSeq-280-contigs-velvet_scores/chromosomes.txt: MiSeq-280-contigs-velvet ../annotations/280_flxplus.gbk
	mauvego MiSeq-280-contigs-velvet ../annotations/280_flxplus.gbk MiSeq-280-contigs-velvet

MiSeq-280-scaffolds-velvet: ../assemblies/velvet/MiSeq-280-scaffolds.fna ../annotations/280_flxplus.gbk
	rm -f MiSeq-280-scaffolds-velvet
	ln -s ../assemblies/velvet/MiSeq-280-scaffolds.fna MiSeq-280-scaffolds-velvet

MiSeq-280-scaffolds-velvet_scores/chromosomes.txt: MiSeq-280-scaffolds-velvet ../annotations/280_flxplus.gbk
	mauvego MiSeq-280-scaffolds-velvet ../annotations/280_flxplus.gbk MiSeq-280-scaffolds-velvet

IonTorrent-1-newbler: ../assemblies/newbler/IonTorrent-1.fna ../annotations/280_flxplus.gbk
	rm -f IonTorrent-1-newbler
	ln -s ../assemblies/newbler/IonTorrent-1.fna IonTorrent-1-newbler

IonTorrent-1-newbler_scores/chromosomes.txt: IonTorrent-1-newbler ../annotations/280_flxplus.gbk
	mauvego IonTorrent-1-newbler ../annotations/280_flxplus.gbk IonTorrent-1-newbler

IonTorrent-2-newbler: ../assemblies/newbler/IonTorrent-2.fna ../annotations/280_flxplus.gbk
	rm -f IonTorrent-2-newbler
	ln -s ../assemblies/newbler/IonTorrent-2.fna IonTorrent-2-newbler

IonTorrent-2-newbler_scores/chromosomes.txt: IonTorrent-2-newbler ../annotations/280_flxplus.gbk
	mauvego IonTorrent-2-newbler ../annotations/280_flxplus.gbk IonTorrent-2-newbler

IonTorrent-both-newbler: ../assemblies/newbler/IonTorrent-1+2.fna ../annotations/280_flxplus.gbk
	rm -f IonTorrent-both-newbler
	ln -s ../assemblies/newbler/IonTorrent-1+2.fna IonTorrent-both-newbler

IonTorrent-both-newbler_scores/chromosomes.txt: IonTorrent-both-newbler ../annotations/280_flxplus.gbk
	mauvego IonTorrent-both-newbler ../annotations/280_flxplus.gbk IonTorrent-both-newbler

454Junior-2-mira: ../assemblies/mira/454Junior-2_out.unpadded.fasta ../annotations/280_flxplus.gbk
	rm -f 454Junior-2-mira
	ln -s ../assemblies/mira/454Junior-2_out.unpadded.fasta 454Junior-2-mira

454Junior-2-mira_scores/chromosomes.txt: 454Junior-2-mira ../annotations/280_flxplus.gbk
	mauvego 454Junior-2-mira ../annotations/280_flxplus.gbk 454Junior-2-mira

454Junior-both-mira: ../assemblies/mira/454Junior-both_out.unpadded.fasta ../annotations/280_flxplus.gbk
	rm -f 454Junior-both-mira
	ln -s ../assemblies/mira/454Junior-both_out.unpadded.fasta 454Junior-both-mira

454Junior-both-mira_scores/chromosomes.txt: 454Junior-both-mira ../annotations/280_flxplus.gbk
	mauvego 454Junior-both-mira ../annotations/280_flxplus.gbk 454Junior-both-mira

454Junior-1-mira: ../assemblies/mira/454Junior-1_out.unpadded.fasta ../annotations/280_flxplus.gbk
	rm -f 454Junior-1-mira
	ln -s ../assemblies/mira/454Junior-1_out.unpadded.fasta 454Junior-1-mira

454Junior-1-mira_scores/chromosomes.txt: 454Junior-1-mira ../annotations/280_flxplus.gbk
	mauvego 454Junior-1-mira ../annotations/280_flxplus.gbk 454Junior-1-mira

MiSeq-280-contigs-mira: ../assemblies/mira/MiSeq-1_out.unpadded.fasta ../annotations/280_flxplus.gbk
	rm -f MiSeq-280-contigs-mira
	ln -s ../assemblies/mira/MiSeq-1_out.unpadded.fasta MiSeq-280-contigs-mira

MiSeq-280-contigs-mira_scores/chromosomes.txt: MiSeq-280-contigs-mira ../annotations/280_flxplus.gbk
	mauvego MiSeq-280-contigs-mira ../annotations/280_flxplus.gbk MiSeq-280-contigs-mira

IonTorrent-1-mira: ../assemblies/mira/IonTorrent-1_out.unpadded.fasta ../annotations/280_flxplus.gbk
	rm -f IonTorrent-1-mira
	ln -s ../assemblies/mira/IonTorrent-1_out.unpadded.fasta IonTorrent-1-mira

IonTorrent-1-mira_scores/chromosomes.txt: IonTorrent-1-mira ../annotations/280_flxplus.gbk
	mauvego IonTorrent-1-mira ../annotations/280_flxplus.gbk IonTorrent-1-mira

IonTorrent-both-mira: ../assemblies/mira/IonTorrent-both_out.unpadded.fasta ../annotations/280_flxplus.gbk
	rm -f IonTorrent-both-mira
	ln -s ../assemblies/mira/IonTorrent-both_out.unpadded.fasta IonTorrent-both-mira

IonTorrent-both-mira_scores/chromosomes.txt: IonTorrent-both-mira ../annotations/280_flxplus.gbk
	mauvego IonTorrent-both-mira ../annotations/280_flxplus.gbk IonTorrent-both-mira

IonTorrent-2-mira: ../assemblies/mira/IonTorrent-2_out.unpadded.fasta ../annotations/280_flxplus.gbk
	rm -f IonTorrent-2-mira
	ln -s ../assemblies/mira/IonTorrent-2_out.unpadded.fasta IonTorrent-2-mira

IonTorrent-2-mira_scores/chromosomes.txt: IonTorrent-2-mira ../annotations/280_flxplus.gbk
	mauvego IonTorrent-2-mira ../annotations/280_flxplus.gbk IonTorrent-2-mira

MiSeq-280-contigs.clc.fasta: ../assemblies/clc/MiSeq-280-contigs.clc.fasta ../annotations/280_flxplus.gbk
	rm -f MiSeq-280-contigs.clc.fasta
	ln -s ../assemblies/clc/MiSeq-280-contigs.clc.fasta MiSeq-280-contigs.clc.fasta

MiSeq-280-contigs.clc.fasta_scores/chromosomes.txt: MiSeq-280-contigs.clc.fasta ../annotations/280_flxplus.gbk
	mauvego MiSeq-280-contigs.clc.fasta ../annotations/280_flxplus.gbk MiSeq-280-contigs.clc.fasta

MiSeq-280-scaffolds.clc.fasta: ../assemblies/clc/MiSeq-280-scaffolds.clc.fasta ../annotations/280_flxplus.gbk
	rm -f MiSeq-280-scaffolds.clc.fasta
	ln -s ../assemblies/clc/MiSeq-280-scaffolds.clc.fasta MiSeq-280-scaffolds.clc.fasta

MiSeq-280-scaffolds.clc.fasta_scores/chromosomes.txt: MiSeq-280-scaffolds.clc.fasta ../annotations/280_flxplus.gbk
	mauvego MiSeq-280-scaffolds.clc.fasta ../annotations/280_flxplus.gbk MiSeq-280-scaffolds.clc.fasta

all: 454Junior-1-newbler_scores/chromosomes.txt
all: 454Junior-2-newbler_scores/chromosomes.txt
all: 454Junior-both-newbler_scores/chromosomes.txt
all: MiSeq-280-contigs-velvet_scores/chromosomes.txt
all: MiSeq-280-scaffolds-velvet_scores/chromosomes.txt
all: IonTorrent-1-newbler_scores/chromosomes.txt
all: IonTorrent-2-newbler_scores/chromosomes.txt
all: IonTorrent-both-newbler_scores/chromosomes.txt
all: 454Junior-2-mira_scores/chromosomes.txt
all: 454Junior-both-mira_scores/chromosomes.txt
all: 454Junior-1-mira_scores/chromosomes.txt
all: MiSeq-280-contigs-mira_scores/chromosomes.txt
all: IonTorrent-1-mira_scores/chromosomes.txt
all: IonTorrent-both-mira_scores/chromosomes.txt
all: IonTorrent-2-mira_scores/chromosomes.txt
all: MiSeq-280-contigs.clc.fasta_scores/chromosomes.txt
all: MiSeq-280-scaffolds.clc.fasta_scores/chromosomes.txt
